AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Time Locker Analyzer
Globals:
  Function:
    Timeout: 60
Parameters:
  evernoteToken:
    Type: String
  evernoteConsumerKey:
    Type: String
  evernoteConsumerSecret:
    Type: String

Resources:
  EvernoteWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.evernoteWebhookEndpoint
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
          EVERNOTE_TOKEN: !Ref evernoteToken
          EVERNOTE_CONSUMER_KEY: !Ref evernoteConsumerKey
          EVERNOTE_CONSUMER_SECRET: !Ref evernoteConsumerSecret
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
        - S3CrudPolicy:
            BucketName: !Ref PlayResultBucket
      Events:
        EvernoteWebhookGet:
          Type: Api
          Properties:
            Path: /evernote-webhook
            Method: get

  EvernoteNoteAnalyzer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.analyzeEvernoteNoteApi
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
          EVERNOTE_TOKEN: !Ref evernoteToken
          EVERNOTE_CONSUMER_KEY: !Ref evernoteConsumerKey
          EVERNOTE_CONSUMER_SECRET: !Ref evernoteConsumerSecret
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
        - S3CrudPolicy:
            BucketName: !Ref PlayResultBucket
      Events:
        EvernoteNoteAnalyzerGet:
          Type: Api
          Properties:
            Path: /evernote/note/analyzer
            Method: get

  ScreenShotAnalyzer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.analyzeScreenShotApi
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
      Events:
        ScreenShotAnalyzerPost:
          Type: Api
          Properties:
            Path: /screen-shot/analyzer
            Method: post

  ScreenShotAnalyzerTestPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.screenShotAnalyzerTestPage
      Runtime: nodejs10.x
      Events:
        ScreenShotAnalyzerTestPageGet:
          Type: Api
          Properties:
            Path: /ui/screen-shot/analyzer
            Method: get
            
  ArmamentsExtracter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-python/
      Handler: app.extract_armaments
      Runtime: python3.7

  PlayResultBucket:
    Type: AWS::S3::Bucket