AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Time Locker Analyzer
Globals:
  Function:
    Timeout: 60
Parameters:
  evernoteToken:
    Type: String
  evernoteConsumerKey:
    Type: String
  evernoteConsumerSecret:
    Type: String

Resources:

  ################################
  # API Resources
  ################################
  EvernoteWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.evernoteWebhookEndpoint
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
          EVERNOTE_TOKEN: !Ref evernoteToken
          EVERNOTE_CONSUMER_KEY: !Ref evernoteConsumerKey
          EVERNOTE_CONSUMER_SECRET: !Ref evernoteConsumerSecret
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
        - S3CrudPolicy:
            BucketName: !Ref PlayResultBucket
      Events:
        EvernoteWebhookGet:
          Type: Api
          Properties:
            Path: /evernote-webhook
            Method: get

  EvernoteNoteAnalyzer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.analyzeEvernoteNoteApi
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
          EVERNOTE_TOKEN: !Ref evernoteToken
          EVERNOTE_CONSUMER_KEY: !Ref evernoteConsumerKey
          EVERNOTE_CONSUMER_SECRET: !Ref evernoteConsumerSecret
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
        - S3CrudPolicy:
            BucketName: !Ref PlayResultBucket
      Events:
        EvernoteNoteAnalyzerGet:
          Type: Api
          Properties:
            Path: /evernote/note/analyzer
            Method: get

  ScreenShotAnalyzer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.analyzeScreenShotApi
      Runtime: nodejs10.x
      Environment:
        Variables:
          ARMAMENT_EXTRACTER_LAMBDA_NAME: !Ref ArmamentsExtracter
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ArmamentsExtracter
        - RekognitionDetectOnlyPolicy: {}
      Events:
        ScreenShotAnalyzerPost:
          Type: Api
          Properties:
            Path: /screen-shot/analyzer
            Method: post

  ScreenShotAnalyzerTestPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.screenShotAnalyzerTestPage
      Runtime: nodejs10.x
      Events:
        ScreenShotAnalyzerTestPageGet:
          Type: Api
          Properties:
            Path: /ui/screen-shot/analyzer
            Method: get

  GetCharacterAverageScore:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.getCharacterAverageScore
      Runtime: nodejs10.x
      Environment:
        Variables:
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
          ATHENA_RESULT_BUCKET: !Ref AthenaResultBucket
      Role: !GetAtt AthenaExecutionRole.Arn
      Events:
        GetCharacterAverageScoreApi:
          Type: Api
          Properties:
            Path: /score/character-average
            Method: get

  GetCharacterHighscore:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.getCharacterHighscore
      Runtime: nodejs10.x
      Environment:
        Variables:
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
          ATHENA_RESULT_BUCKET: !Ref AthenaResultBucket
      Role: !GetAtt AthenaExecutionRole.Arn
      Events:
        GetCharacterHighscoreGet:
          Type: Api
          Properties:
            Path: /score/character-high
            Method: get

  GetScorePerArmlevel:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.getScorePerArmlevel
      Runtime: nodejs10.x
      Environment:
        Variables:
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
          ATHENA_RESULT_BUCKET: !Ref AthenaResultBucket
      Role: !GetAtt AthenaExecutionRole.Arn
      Events:
        GetScorePerArmlevelApi:
          Type: Api
          Properties:
            Path: /arms/score-per-level
            Method: get

  UpdateS3Objects:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-nodejs/
      Handler: index.updateS3Objects
      Runtime: nodejs10.x
      Timeout: 900
      Environment:
        Variables:
          PLAY_RESULT_BUCKET: !Ref PlayResultBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PlayResultBucket

  AthenaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: AthenaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action: "athena:*"
              Resource: "*"
            - Effect: "Allow"
              Action: "glue:*"
              Resource: "*"
            - Effect: "Allow"
              Action: "s3:*"
              Resource: "*"

  ################################
  # Lambda Resource
  ################################
  ArmamentsExtracter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: time-locker-python/
      Handler: app.extract_armaments
      Runtime: python3.7

  ################################
  # S3 Resource
  ################################
  PlayResultBucket:
    Type: AWS::S3::Bucket
  AthenaResultBucket:
    Type: AWS::S3::Bucket

  ################################
  # Glue Resources
  ################################
  MyRole: # ここのサンプルまま: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  TimeLockerDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: time-locker
      CatalogId: !Ref AWS::AccountId

  PlayResultCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: !GetAtt MyRole.Arn
      DatabaseName: !Ref TimeLockerDatabase
      Targets:
        S3Targets:
          - Path: !Ref PlayResultBucket